# Generated by Django 4.2.20 on 2025-05-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_company_vendor_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_code', models.CharField(max_length=100, unique=True)),
                ('jenis_part', models.CharField(choices=[('filer', 'Filer')], max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ManyToManyField(blank=True, null=True, related_name='parts', to='master.vendor')),
            ],
        ),
    ]
