# Generated by Django 4.2.20 on 2025-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_part_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='chassis_number',
            field=models.CharField(max_length=255),
        ),
    ]
