# Generated by Django 4.2.20 on 2025-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_truck_chassis_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
