# Generated by Django 4.2.24 on 2025-10-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_product_spbu'),
    ]

    operations = [
        migrations.AddField(
            model_name='spbu',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spbu',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
