# Generated by Django 4.2.24 on 2025-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_spbu_address2_spbu_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spbu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spbu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
