# Generated by Django 4.2.20 on 2025-05-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_alter_part_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency')], max_length=50)),
                ('booking_date', models.DateField()),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('odometer_reading', models.IntegerField()),
                ('service_location', models.CharField(max_length=250)),
                ('technician_name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('input_by', models.IntegerField()),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.truck')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RecordParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.part')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.record')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('log_description', models.TextField()),
                ('updated_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.record')),
            ],
        ),
    ]
