# Generated by Django 4.2.20 on 2025-05-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='truck_id',
            new_name='truck',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
