# Generated by Django 4.2.20 on 2025-05-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_truck_chassis_number_alter_truck_engine_number'),
        ('maintenance', '0003_alter_log_log_type_alter_record_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vendor'),
        ),
    ]
