# Generated by Django 4.2.24 on 2025-10-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_record_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='odometer_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
