# Generated by Django 4.2.24 on 2025-11-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_spbu_created_at_alter_spbu_updated_at'),
        ('maintenance', '0005_alter_record_odometer_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.truck')),
            ],
        ),
    ]
